### ISSUE TITLE
Warning: Reference to Free Variable

### ISSUE THREAD

**Issue by angelic-sedition** [immerrr/ample-regexps.el#4]
I'm trying to use ample-regexps for a package. When loading the file or eval-ing something created with `define-arx`, it works exactly as expected. However, when compiling the file (specifically running package-install-file), I get errors. For example, if I've created "my-rx" with define-arx and then try to create a variable holding something like `(my-rx (or bol " ")`, I'll get "Warning: reference to free variable `bol'". I get the same warnings for any custom things in the define-arx I add and then try to use.

Am I misunderstanding how ample-regexps is supposed to work? If this is caused by a totally unrelated error on my part, then I apologize.

**Comment by immerrr** [comment]
Can you provide a self-contained example?

One thing from the top of my head is that `my-rx` is a macro and you'll probably need to do `(eval-when-compile (require 'ample-regexps))`.  Function version of the same thing that is not expanded during compilation is called `my-rx-to-string`.

**Comment by angelic-sedition** [comment]
This is a minimal example.
```
;;; my-ample-test.el --- Test of my failures.

;; Package-Requires: ((ample-regexps "0.1"))
;; Version: 0.1

;;; Code:
(eval-when-compile (require 'ample-regexps))

(define-arx my-rx
  '((left-quotes (in "\"“`'"))))

(defvar my-regexp
  (my-rx (or bol " ") (0+ left-quotes)))

(provide 'my-ample-test)
;;; my-ample-test.el ends here
```
And the warning output from `package-install-file`:
```
my-ample-test.el:14:14:Warning: reference to free variable `bol'
my-ample-test.el:14:28:Warning: reference to free variable `left-quotes'

In end of data:
my-ample-test.el:18:1:Warning: the following functions might not be defined at runtime: arx--to-rx,
    arx--form-make-docstring
my-ample-test.el:18:1:Warning: the following functions are not known to be defined:
    my-rx-to-string, my-rx, 0+
```
I'm guessing that this isn't ample-regexp's fault and I'm just not getting something. Is it obvious what I'm doing wrong?

**Comment by immerrr** [comment]
This the type of fun you get with macros and byte-compilation.

As I have stated above, `my-rx` is a macro (analogous to `rx` macro) and its function counterpart is `my-rx-to-string`, one of the difference between macros and functions is that macros get expanded in compile-time. With that being said let's get back to your example.

You're byte-compiling `(defvar my-regexp (some-macro ...))` and byte-compiler will try to expand this macro. `define-arx` is a macro, too, and so it will also be expanded. Its expansion among other things contains `(defmacro my-rx ...)` and all defmacros are also evaluated in compile-time (so that further references of such macros can be expanded, too). The problem is that the expansion also contains helper functions (e.g. `my-rx-to-string`) which are not usually evaluated during compilation. This is addressed in d5194b2 and should fix "are not known to be defined" and "reference to free variable" errors.

Another series of errors, "might not be defined at runtime" ones, are there because the `(require ample-regexps)` form should be in fact put into `eval-and-compile`. The problem is that `eval-when-compile` forms are evaluated ONLY at compile-time and the require is not evaluated when you try to load this file afterwards thus missing some other helper functions found in the module.

**Comment by immerrr** [comment]
Please see if my fix resolves the issue for you. And thank you for trying out ample-regexps.

**Comment by angelic-sedition** [comment]
Thanks a lot for explaining that. With that commit, it does compile and work as expected. Also, thanks for the awesome package. It does exactly what I wished I could do when I first found rx and more.
